import Head from "next/head";
import Layout from "../components/Layout";

export default function Home() {
  return (

      <Layout>

          <div>
            <Head>
              <title>Pizzaria LF</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/Logo.png" />
            </Head>
            {/* body */}
            <main>
              <h1>Feito por Luys Fernnando</h1>
            </main>
          </div>
      </Layout>
  );
}

